### ISSUE TITLE
yaml not working

### ISSUE THREAD

**Issue by oznav2** [npiv/chatblade#45]
when i am placing a file called expert.yaml or anything else on the config folder as instructed i get error invoking the command :

chatblade -p expert <some text>

no prompt expert found in any of following locations:
 - expert
 - ~/.config/chatblade/expert

**Comment by npiv** [comment]
Hi @oznav2

yaml was phased out quite a few versions ago as it didn't make sense since it only contained one thing. Please see last example in readme. 

Change your prompt file to just expert with only text inside containing the prompt and it should work. Hopefully that should be easier moving forward as well.

Let me know if you have any issues
